# Generated by Django 3.1.2 on 2021-02-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apps',
            new_name='App',
        ),
    ]
